n1 = float(input("enter first number: "))
n2 = float(input("enter second number: "))
print("Add =", n1 + n2)
print("Subtraction =", n1 - n2)
print("Multiplication =", n1 * n2)
print("Division =", n1 / n2)
print("Modulus =", n1 % n2)